/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
  // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
  id("org.jetbrains.kotlin.jvm").version("1.3.21")
}

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

dependencies {
  implementation("com.google.guava:guava:27.1-jre")
  
  implementation("org.assertj:assertj-core:3.12.2")
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  implementation("org.reflections:reflections:0.9.11")

  // TEST
  val jUnitVersion = "5.3.1"
  testImplementation("org.junit.jupiter:junit-jupiter-api:$jUnitVersion")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$jUnitVersion")
}

tasks {
  withType<Test> {
    useJUnitPlatform()
  }
}
