/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
  val kotlinVersion = "1.3.21"
  kotlin("jvm") version kotlinVersion
  kotlin("kapt") version kotlinVersion
}

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

//dependencies {
//  implementation("com.github.cretz.kastree:kastree-ast-psi:0.4.0")
//
//  implementation("com.google.guava:guava:27.1-jre")
//  implementation("com.google.auto.service:auto-service:1.0-rc5")
//
//  implementation("org.assertj:assertj-core:3.12.2")
//  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
//  implementation("org.reflections:reflections:0.9.11")
//
//  kapt(project(":generator"))
//
//  compileOnly(project(":generator"))
//
//
//  // TEST
//  val jUnitVersion = "5.3.1"
//  testImplementation("org.junit.jupiter:junit-jupiter-api:$jUnitVersion")
//  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$jUnitVersion")
//}
//
//tasks {
//  withType<Test> {
//    useJUnitPlatform()
//  }
//}
//
//sourceSets {
//  main {
//    java {
//      srcDirs("${buildDir.absolutePath}/tmp/kapt/main/kotlinGenerated/")
//    }
//  }
//}
//
//kapt {
//  useBuildCache = true
//}