/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
  val kotlinVersion = "1.3.21"
  kotlin("jvm") version kotlinVersion
  kotlin("kapt") version kotlinVersion
}

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}
